---

# SPDX-FileCopyrightText: 2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.25.0"
    file:
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-souvap.yaml"
      - "jobs/package-and-publish-helm-charts-souvap.yaml"
      - "jobs/check-debian-updates.yaml"

variables:
  POETRY_VERSION: "1.6.1"

lint-pre-commit:
  before_script:
    - "helm repo add bitnami https://charts.bitnami.com/bitnami"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "selfservice-invitation"
    KANIKO_BUILD_CONTEXT: $CI_PROJECT_DIR
    DOCKERFILE_PATH: "docker/selfservice-invitation/Dockerfile"

container-build:
  parallel:
    matrix: *build-matrix

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

push-image-souvap:
  parallel:
    matrix: *build-matrix

container-sign-souvap:
  parallel:
    matrix: *build-matrix

check-debian-updates:
  parallel:
    matrix: *build-matrix
  variables:
    TARGET_IMAGE: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest"

test_selfservice-invitation:
  stage: test
  image: docker-registry.knut.univention.de/python:3.11-slim
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: "never"
    - when: "on_success"
  script:
    - pip install poetry=="$POETRY_VERSION"
    - poetry config --local virtualenvs.create false
    - poetry install --with dev
    - pytest --cov --cov-report=term --cov-report=xml:coverage.xml --cov-branch
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
...
