---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.9.9"
    file:
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "templates/souvap.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build.yaml"
      - "jobs/package-and-publish-helm-charts.yaml"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "selfservice-listener"
    KANIKO_BUILD_CONTEXT: $CI_PROJECT_DIR
    DOCKERFILE_PATH: "docker/selfservice-listener/Dockerfile"

container-build:
  parallel:
    matrix: *build-matrix

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

publish-images:
  extends: .push-image-souvap
  parallel:
    matrix: *build-matrix

publish-helm-charts-souvap:
  extends: .publish-helm-charts-souvap
...
