---
{{ include "common.secret" (dict "top" . "overrides" "selfservice-listener.secret") }}

{{- define "selfservice-listener.secret" }}
{{- with .top }}
data:
  ldap_secret: {{ .Values.selfserviceListener.ldapPassword | b64enc | quote }}
  ca_cert: {{ .Values.selfserviceListener.caCert | quote }}
  cert_pem: {{ .Values.selfserviceListener.certPem | quote }}
{{- end }}
{{- end }}
